winton-active_wrapper:
  repo: git@github.com:winton/active_wrapper.git
  path: vendor
winton-secret_key:
  repo: git@github.com:winton/secret_key.git
  path: vendor
sinatra:
  repo: git://github.com/sinatra/sinatra.git
  path: vendor
webrat:
  repo: git://github.com/brynary/webrat.git
  path: vendor