production:
  imap:
    password: password
    port: 993
    server: imap.gmail.com
    ssl: true
    use_login: true
    username: test@mydomain.com
  smtp:
    address: smtp.gmail.com
    authentication: :plain
    domain: mydomain.com
    password: password
    port: 587
    enable_starttls_auto: true
    user_name: test@mydomain.com